
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 25 12:06:44 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATEROREQ = 21;
  public static final int AND = 26;
  public static final int SEMICOLON = 9;
  public static final int NOTEQ = 19;
  public static final int SELECT = 14;
  public static final int STRINGCONST = 33;
  public static final int OR = 27;
  public static final int EQUAL = 18;
  public static final int CHAR = 13;
  public static final int LEFTPAR = 24;
  public static final int END = 3;
  public static final int GREATER = 20;
  public static final int INTCONST = 29;
  public static final int RIGHTPAR = 25;
  public static final int COLON = 7;
  public static final int ID = 28;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int BOOLEAN = 12;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CHARCONST = 32;
  public static final int LESSOREQ = 17;
  public static final int DOUBLECONST = 30;
  public static final int CASE = 15;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int ASSIGN = 22;
  public static final int INTEGER = 10;
  public static final int REAL = 11;
  public static final int BOOLCONST = 31;
  public static final int LESS = 16;
  public static final int EPSYLON = 5;
  public static final int LAMBDA = 23;
}

